# Generated by Django 4.0.4 on 2022-04-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catergory',
            new_name='category',
        ),
    ]
