# Generated by Django 4.0.4 on 2022-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tweitter_url',
            new_name='twitter_url',
        ),
    ]
